### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by OKNoah** [scriptin/brackets-indent-softwraps#1]
Is it possible to install this through the GUI? I can't seem to find it searching.

**Comment by ghost** [comment]
I'm pretty sure I installed it via the URL in extension manager. It's been a while since I used Brackets though so I'm not 100% sure.

**Comment by OKNoah** [comment]
Oh, just tried that and made a new ticket for it at #2

**Comment by scriptin** [comment]
I couldn't add it to [Brackets Extension Registry](https://brackets-registry.aboutweb.com/) back when it was ready. It showed me some obscure error, I couldn't figure out what it was. I'll try again this weekend.

**Comment by peterflynn** [comment]
@scriptin If you get an error again, please [file a bug](https://github.com/adobe/brackets/issues/new) with details and point us to a copy of the ZIP file.

In the past we've seen some problems with ZIP files created using Finder on the Mac.  Maybe try the "Download ZIP" button that GitHub offers  and see if that works any better -- that's how I upload all my extensions and it's never failed me so far :-)
