### ISSUE TITLE
Left padding of editor view

### ISSUE THREAD

**Issue by chris-scheurle** [scriptin/brackets-indent-softwraps#13]
There is a problem with [some designs](http://github.com/thomhines/tonights-specials/issues/1#issuecomment-160504137), that specify a `padding-left` other than `0`for `#editor-holder .CodeMirror pre`.

Could you please check for any _existing_ padding on the element, and add that to the one _you_ apply directly to the element? :smile:
![Screenshot](http://demos.scheurle.info/screenshots/20151130034905.png)

**Comment by scriptin** [comment]
I don't know if there's any way to extract a `padding-left` value set by a theme. These don't work: `window.getComputedStyle(elt).paddingLeft`, `window.getComputedStyle(elt)["padding-left"]`, `window.getComputedStyle(elt).getPropertyValue("padding-left")`. Empty string is returned in all cases. I guess that styles are not applied at the moment I check that, but I can't understand why. I use `AppInit.appReady`, so everything should be loaded, and it's probably not the case that theme is loading after the extension.

Honestly, I think it's impossible to resolve this issue. Docs on Brackets API are kind of atrocious, I can't even understand the lifecycle of an extension. Not to mention this whole extension is based on a hack...

If someone knows a way around that, please let me know.

**Comment by scriptin** [comment]
One possible solution would be to use [`text-indent: ... hanging;`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent), but [no](https://code.google.com/p/chromium/issues/detail?id=360958).

**Comment by chris-scheurle** [comment]
As @scriptin  said:

> These don't work

:cry: ... whatever you did in [0.2.6](http://github.com/scriptin/brackets-indent-softwraps/commit/e0dd6d984e27cfa440d16daa2ec8d57774f58fd6), it **worked** for _me_.

Everything looked like it should, everything looked great. :smile: ... and now it's gone, again. :disappointed:

So, _please_:
- either _re_implement the changes of [0.2.6](http://github.com/scriptin/brackets-indent-softwraps/commit/e0dd6d984e27cfa440d16daa2ec8d57774f58fd6). Maybe it's not a perfect _bugfix_, but at least it was a _partial_ one.
  **Edit**: I just took a look at the [other issue](https://github.com/scriptin/brackets-indent-softwraps/issues/14) referenced above. Ok, I guess it's _not_ an option to do _that_. :grinning:
- _or:_ introduce some settings option for `brackets.json` where I can set a desired "base padding left" _(reflecting the values in the design I'm using)_, manually.

As @scriptin  said:

> One possible solution would be to use `text-indent:` ... `hanging;`, but no.

I don't know anything about coding Brackets plugins and yes, the API docs are kind of ... confusing. But: 
considering there is **no** "everything is loaded, displayed and done" event _(or if there are multiple plugins waiting for that one and changing things_ after _the fact)_: maybe one could use something like `setInterval()` and watch for changes in one of the properties mentioned by you above _(adjusting the padding on change and canceling the interval if nothing has changed for some time)_?

**Comment by chris-scheurle** [comment]
Considering there are _a lot of lines_ to watch and so there woud have to be a _lot of intervals_ to set: maybe one could do something along the lines of my last suggestion using a [`MutationObserver`](https://developer.mozilla.org/de/docs/Web/API/MutationObserver) _(on the_ parent _of all the lines, with `childList: true, attributes: true, attributeOldValue: true, attributeFilter: ['style']`)_, and another one watching for newly added `style` and `link` elements?

**Comment by scriptin** [comment]
Since I need to get the theme-specific `padding-left` only when an editor is loaded or when a different theme is selected, setting a timeout may work. I'll try it later, thanks for your suggestions.

**Comment by macbookandrew** [comment]
So e6e20f61a16f653a55bfc859a23cefbbc04f7b3f fixes the issue I saw with Brackets Beta 1.6…it remains to be seen what happens when the stable release comes out.

**Edit:** to be more specific, it’s adding 4px of padding to _every_ line instead of just empty lines, as the stable version was doing.

**Comment by chris-scheurle** [comment]
**Some new idea:** maybe, you could use `border-left:[...]px solid transparent` and leave `padding-left` completely untouched (I don't think there's many themes that would alter *that* value to something different than `0`)? :smile:

**Comment by chris-scheurle** [comment]
I just uninstalled **brackets-indent-softwraps** _(to reinstall a clean version, after I completely messed up my local version's code)_ and it seems that **[Brackets Release 1.6](http://github.com/adobe/brackets/releases/tag/release-1.6) supports indented softwrapped lines now, out of the box**.

:point_right: No plugin and hence no fixing needed, anymore. :satisfied:

**Comment by scriptin** [comment]
Confirmed: feature is implemented in adobe/brackets/pull/11909
