### ISSUE TITLE
integration with other extension*s

### ISSUE THREAD

**Issue by maxwowpow** [scriptin/brackets-indent-softwraps#4]
Hello & thank you for the extension, wrapped strings look cleanier and nicer!

Is there a chance you could try to determine, whether "SpellCheck" extension interferes with the functionality of "indent-softwraps" and there is a way to fix it? Thanks.

_Repro:_
install spell-check (https://github.com/couzteau/SpellCheck)
install brackets-indent-softwraps.
write some multiline text of random letters to be "soft wrapped".
when text is soft-wrapped select text and run spellCheck (right click >> English e.g.).

_Expected:_
text highlighted on "misspelled" words", soft wrap intact.

_What happens:_
letters overlap:
![2015-02-09 16_13_52-pages_loremipsum html website - brackets](https://cloud.githubusercontent.com/assets/169885/6108909/27e07862-b077-11e4-89d6-a20cc4fe5bd0.jpg)

_Possible problem:_
Both developers assume, that text is **the same / original / not manipulated**.

_Possible solution:_
Check before applying the action whether there was some text manipulation and either **reset it** (?) or **restore it after** (?)

CC: @couzteau
https://github.com/couzteau/SpellCheck

**Comment by scriptin** [comment]
Thank you! Found possible fix, opened an issue: couzteau/SpellCheck/issues/13

**Comment by scriptin** [comment]
By the way, have you seen similar issues with any other extensions?

**Comment by couzteau** [comment]
pushed spellcheck 0.5.8 with proposed fix.

**Comment by maxwowpow** [comment]
Thanks, now it's ok!

_Re: similar issues_
yes and no > #5

**Comment by scriptin** [comment]
I found out what was the issue: http://jsfiddle.net/pr3xc5ny/3/

It is because nested `inline-block` elements were inheriting `text-indent` property. That's what also caused indentation to fail on tabs - see scriptin/brackets-indent-softwraps/pull/3 - that's why  `.cm-tab { display: inline; }` worked.

Version 0.2.1 is out, seems to work OK.

@couzteau As I was afraid of, that was a failure on my part

**Comment by couzteau** [comment]
Hey No worries. Spell check works just fine using `inline`in the context. Thanks for following up.
