### ISSUE TITLE
Small indentation with white-space only lines

### ISSUE THREAD

**Issue by eight04** [scriptin/brackets-indent-softwraps#6]
![](http://i.imgur.com/bHQsvbS.png)

If you append any character to the end of line, the small indentation disappears.

Brackets:
Release 1.1 build 1.1.0-15558 (release ea908cae5) 

Indent softwrapped lines:
0.2.1

**Comment by scriptin** [comment]
Fixed. Thanks for reporting.

`String.prototype.search()` returns `-1` when there are no matches, and than formula `(nonTabsCount + tabsCount * cm.getOption("tabSize")) * cm.defaultCharWidth()` evaluates into `-8`
