### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by alvint** [scriptin/brackets-indent-softwraps#7]
on main.js:28

**Comment by scriptin** [comment]
Thank you!

I wonder how it even worked. Probably bad copy-pasting on my part. 0.2.3 is out

**Comment by alvint** [comment]
Fast!

**Comment by alvint** [comment]
...although now the initial indentation of lines is wrong:

```
foo {
bar { // not indented for some reason
   ...
}
}
```

**Comment by scriptin** [comment]
I can't reproduce it.
- Does "initial" mean when you just open a file?
- What are the symbols before "bar"? Maybe mixed spaces/tabs?

**Comment by scriptin** [comment]
I assume you may have your tab size set to 4, "foo" indented with 1 tab, and "bar" indented with 4 spaces:

```
(TAB)foo {
(SPACE)(SPACE)(SPACE)(SPACE)bar {
```

Then `1tab * 4 == 4spaces * 1`
