### ISSUE TITLE
subsequent indents do not factor in the gutter width

### ISSUE THREAD

**Issue by alvint** [scriptin/brackets-indent-softwraps#8]
Pseudocode. There should be a 3-space gutter, and all indents should be 4 spaces:

```
   // this is not indented; the space to the left is the gutter
   foo { // this is not indented; the space to the left is the gutter
    bar { // this block's indent doesn't account for the gutter so appears unindented
        ...
    }
   } // this is not indented; the space to the left is the gutter
```

**Comment by alvint** [comment]
Sorry, the issue is all lines with no indent are indented one level.

**Comment by alvint** [comment]
Sorry again, the issue is subsequent indents don't account for the gutter (which for some reason is set to one indent size).

**Comment by alvint** [comment]
In other words, there is supposed to be a small "gutter" (blank margin on the left of the editor window). I think the issue is that it's not being factored in to indent calculations properly.

**Comment by alvint** [comment]
Further info: The gutter area can be added to by other plugins so can be of variable size.

**Comment by scriptin** [comment]
Here's how it looks when I try it. First block is indented with 4 spaces per level, second with 1 tab.

![screenshot from 2015-02-11 18 04 20](https://cloud.githubusercontent.com/assets/665888/6149276/b932cca0-b218-11e4-92e7-1c92a01f4951.png)

Seems fine to me. Also works as expected when I turn off line numbers.

Is it a conflict with another extension? If so, which one? If not, can you describe the exact steps of reproducing this?

**Comment by alvint** [comment]
It might be a conflict. I think the only extension I have turned on that adds to the gutter is brackets-git.

**Comment by alvint** [comment]
Notice how the first indent appears half-sized. All indents should be 4 spaces. If the indent were 2 spaces it would appear as if the first indent were missing.

![screen shot 2015-02-11 at 10 12 39 am](https://cloud.githubusercontent.com/assets/622202/6149402/a671ae48-b1d6-11e4-8d36-44067da1a5e0.png)

**Comment by alvint** [comment]
With line numbers turned on the indent appears correct.

**Comment by alvint** [comment]
Same issue with brackets-git removed.

**Comment by scriptin** [comment]
Indeed, it is a conflict with `bracket-git`. Verified. I'll try to figure it out.

**Comment by alvint** [comment]
I removed BG and still have the same issue...

**Comment by scriptin** [comment]
OK, reproduced w/o `brackets-git`

**Comment by alvint** [comment]
I was wrong: the gutter size is respected, but the first indent is small for some reason.

**Comment by scriptin** [comment]
Localized the problem:

on each indented line (`<pre>` element), extension sets `padding-left` to absolute value calculated by the formula. And there is a style rule which says `.CodeMirror pre{padding:0 15px 0 0}` - this gets overwritten, which is equivalent to just removing the gutter.

When line numbers are turned on, there is an additional element in front of `<pre>`, which counteracts the issue:

```
<div class="CodeMirror-gutter-wrapper" style="left: -60px; width: 60px;">
    <div class="CodeMirror-linenumber CodeMirror-gutter-elt" style="left: 0px; width: 35px;">
        LINE_NUMBER_HERE
    </div>
</div>
```

That's why it works with line numbers on.

**Comment by alvint** [comment]
Yup!

**Comment by scriptin** [comment]
Used dirty hack for this one. Gutter (`padding-left: 15px;`) is added only when line numbers are off. 

I wanted to read this value (`15px`) from computed style, but this is impossible in general: if line numbers are on when editor is started, class which triggers the rule (`show-line-padding`) is not added to outer `<div>`. This class gets added when I toggle showing line numbers, but I don't know how to force it when it is missing.

Here is the rule which adds extra 15 pixels when line numbers are on (found in `brackets.min.css`):

```
.show-line-padding .CodeMirror pre { padding-left:15px }
```

That was rough...
